# Generated by Django 5.2 on 2025-05-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warga_kampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Pengaduan', 'Pengaduan'), ('Verifikasi', 'Verifikasi'), ('Sistem', 'Sistem')], max_length=50)),
                ('pesan', models.TextField()),
                ('status_baca', models.BooleanField(default=False)),
                ('waktu_dikirim', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasis', to='warga_kampus.wargakampus')),
            ],
        ),
    ]
