# Generated by Django 5.2 on 2025-05-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengaduan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManajemenAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('Hapus Akun', 'Hapus Akun'), ('Ubah Peran', 'Ubah Peran')], max_length=50)),
                ('waktu_aksi', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akun_dikelola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminVerifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_verifikasi', models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('waktu_verifikasi', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
            ],
        ),
    ]
