# Generated by Django 5.2 on 2025-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmanajemenakun',
            old_name='pengguna',
            new_name='user_yang_dikelola',
        ),
        migrations.AddField(
            model_name='adminmanajemenakun',
            name='catatan_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminmanajemenakun',
            name='aksi',
            field=models.CharField(choices=[('Nonaktifkan Akun', 'Nonaktifkan Akun'), ('Aktifkan Akun', 'Aktifkan Akun'), ('Hapus Akun', 'Hapus Akun')], max_length=50),
        ),
    ]
