# Generated by Django 5.2 on 2025-05-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warga_kampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='pengaduan_images/')),
                ('lokasi', models.CharField(max_length=255)),
                ('tanggal_kejadian', models.DateField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Menunggu', editable=False, max_length=10)),
                ('verifikasi', models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Belum Diverifikasi', editable=False, max_length=20)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga_kampus.wargakampus')),
            ],
        ),
    ]
