# Generated by Django 5.2 on 2025-05-10 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LampiranPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lampiran_pengaduan/')),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('uraian', models.TextField()),
                ('tanggal_kejadian', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('diverifikasi', 'Terverifikasi'), ('diproses', 'Sedang Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi')], default='sedang', max_length=10)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('tanggal_penanganan', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pengaduan.kategoripengaduan')),
            ],
        ),
    ]
