# Generated by Django 5.2 on 2025-05-10 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengaduan', '0001_initial'),
        ('pihak_kampus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan_diajukan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='penangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaduan_ditangani', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='pihak_terkait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pihak_kampus.department'),
        ),
        migrations.AddField(
            model_name='lampiranpengaduan',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='pengaduan.pengaduan'),
        ),
    ]
