# Generated by Django 5.2 on 2025-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga_kampus', '0002_wargakampus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wargakampus',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
