# Generated by Django 5.2 on 2025-05-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PihakKampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kampus', models.CharField(default='UMS', max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PihakKampusPengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kampus', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Menunggu', max_length=10)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
                ('pihak_kampus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pihak_kampus.pihakkampus')),
            ],
        ),
    ]
