# Generated by Django 5.2 on 2025-05-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Sangat Tidak Puas'), (2, 'Tidak Puas'), (3, 'Netral'), (4, 'Puas'), (5, 'Sangat Puas')])),
                ('komentar', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('dibaca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
