# Generated by Django 5.2 on 2025-05-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Tidak Puas'), (2, 'Kurang Puas'), (3, 'Cukup'), (4, 'Puas'), (5, 'Sangat Puas')])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pengaduan.pengaduan')),
            ],
        ),
    ]
