# Generated by Django 5.2 on 2025-05-10 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pengaduan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pengaduan.pengaduan'),
        ),
    ]
